weights: ''
cfg: models/yolov5s-classic-80.yaml
data: data/coco.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 8
img_size:
- 640
- 640
resume: false
nosave: false
notest: false
workers: 0
device: '0'
single_cls: false
rect: false
noautoanchor: false
evolve: false
multi_scale: true
label_smoothing: 0.0
adam: false
sync_bn: false
linear_lr: false
cache_images: false
image_weights: true
bucket: ''
project: ./runs/train/coco-32bit
name: exp
exist_ok: false
quad: false
save_period: -1
artifact_alias: latest
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
save_dir: runs/train/coco-32bit/exp1
